import { CollectionState } from "./collection";
import { LoadAction } from "../actions";
import { CollectionData, LinkData } from "../interfaces";
export declare function shouldClear(newCollection: CollectionData, oldCollection: CollectionData): boolean;
export declare function addLink(history: LinkData[], link: LinkData): LinkData[];
export declare function addCollection(history: LinkData[], collection: CollectionData): LinkData[];
export declare function shorten(history: LinkData[], newUrl: string): LinkData[];
export declare function shouldAddRoot(newCollection: CollectionData): boolean;
export declare function onlyRoot(newCollection: CollectionData): LinkData[];
declare const _default: (state: CollectionState, action: LoadAction<CollectionData>) => LinkData[];
export default _default;
